spring.application.name=examFinal_Spring
spring.datasource.url=jdbc:postgresql://localhost:5432/exam_poo_db
spring.datasource.username=postgres
spring.datasource.password=jacko
spring.datasource.driver-class-name=org.postgresql.Driver